### ISSUE TITLE
Set up email provider

### ISSUE THREAD

**Issue by Ilidur** [EOF-Hackspace/Operations#7]
@MetaFight is interested in having a hosted email service.
From a discussion on DigitalOxford asking the same question these were provided:
> https://soverin.net, proton mail are two that spring to mind

Whoever takes this should come with a proposal of costs, admin and security possibilities.

**Comment by MetaFight** [comment]
I've already found a service that would allow us 10 free mailboxes with a (very) limited number of outgoing daily emails.

This is not suitable as a compete email solution, but it's entirely free, and is sufficient for our current modest needs.

Eventually, going though a domain registrar like crazy domains might be a suitable option as the email per user per month rate is better than most fully hosted services... and we could potentially script the creation/deletion of accounts.

**Comment by MetaFight** [comment]
I ended up paying (out of personal pocket) for the CrazyDomains email service for one year.
We'll need to revisit this when the year is up.
